# The site is already built — it is static files generated by cmd/docgen in
# the flockdeck repository — so there is nothing to compile here. nginx serves
# what the repository holds.
#
# Everything that is not the site is kept out by .dockerignore rather than
# named here, so a page added to the site is served without this file having
# to hear about it.
#
# The base is pinned to nginx's minor version, the one docs.flockdeck.ai runs,
# so a rebuild picks up its patch releases and never a new minor on its own;
# moving to the next one is a change made here, and reviewed. Kept level with
# flockdeck-site's own pin.
FROM nginx:1.31-alpine

COPY . /usr/share/nginx/html

# The server's configuration arrives with the site and is moved out of it, so
# there is still one COPY to reason about and the file is not served as a page.
RUN mv /usr/share/nginx/html/nginx.conf /etc/nginx/conf.d/default.conf
