#!/usr/bin/env bash
# Everything to do with the generated half of the site.
#
#   generated.sh regenerate [TAG]   regenerate the site in place from flockdeck
#                                   TAG (default: latest release) and record
#                                   it in .docs-generated-from
#   generated.sh check              the checked-in generated files are exactly
#                                   what the stamped flockdeck version makes
#                                   (fails on hand edits and on content/*.md
#                                   changes nobody regenerated for)
#   generated.sh upstream REPORT    regenerate from flockdeck's LATEST release
#                                   into a scratch copy and write REPORT: empty
#                                   when the site is current, else the pages
#                                   that would change. Always exits 0 if it ran.
#
# The site's app/ and self-hosting/ pages are generated by cmd/docgen in
# Flockdeck/flockdeck from internal/help/pages/*.md plus this repo's
# content/self-hosting/*.md. .docs-generated-from is "<tag> <commit>" of the
# flockdeck the checked-in pages came from: check compares against that, never
# against the newest release, so a flockdeck release never turns an unrelated
# docs PR red. Whether the docs are behind the newest release is `upstream`'s
# question, asked on a schedule.
#
# Runs against the committed tree (git archive HEAD), so it sees what CI sees
# and not a working copy's line endings or uncommitted edits.
set -euo pipefail

repo=Flockdeck/flockdeck
root=$(git rev-parse --show-toplevel)
stamp="$root/.docs-generated-from"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

latest_tag() { gh release view --repo "$repo" --json tagName --jq .tagName; }

# fetch_flockdeck TAG [SHA]: clone flockdeck at TAG into $work/flockdeck,
# refusing if the tag no longer points at SHA (a moved tag is not the
# version that was stamped).
fetch_flockdeck() {
  git -c advice.detachedHead=false -c core.autocrlf=false clone -q --depth 1 --branch "$1" "https://github.com/${repo}.git" "$work/flockdeck" >&2
  local sha
  sha=$(git -C "$work/flockdeck" rev-parse HEAD)
  if [ -n "${2:-}" ] && [ "$sha" != "$2" ]; then
    echo "flockdeck $1 is now $sha, but $stamp says it was generated from $2." >&2
    echo "A release tag was moved. Regenerate with: tools/docdrift/generated.sh regenerate $1" >&2
    exit 1
  fi
  echo "$sha"
}

# generate OUT: run docgen from the fetched flockdeck into OUT, which already
# holds the docs repo's tree (docgen reads content/ from it).
generate() {
  (cd "$work/flockdeck" && go run ./cmd/docgen -out "$1" >/dev/null)
}

# scratch_copy: the committed tree, minus the pages docgen writes, so a page
# docgen no longer produces is a difference rather than a leftover.
scratch_copy() {
  mkdir -p "$work/site"
  git -C "$root" -c core.autocrlf=false archive HEAD | tar -x -C "$work/site"
  rm -rf "$work/site/app" "$work/site/self-hosting"
}

# changed_pages: list what differs between the committed tree and $work/site.
changed_pages() {
  local orig="$work/orig"
  mkdir -p "$orig"
  git -C "$root" -c core.autocrlf=false archive HEAD | tar -x -C "$orig"
  diff -rq "$orig" "$work/site" | sed -E \
    -e "s#^Files $orig/(.*) and $work/site/.* differ\$#changed: \1#" \
    -e "s#^Only in $orig/?(.*): (.*)\$#only in the repo (docgen no longer makes it): \1/\2#" \
    -e "s#^Only in $work/site/?(.*): (.*)\$#missing from the repo (docgen makes it): \1/\2#" \
    -e 's#: /#: #' || true
}

case "${1:-}" in
regenerate)
  tag=${2:-$(latest_tag)}
  sha=$(fetch_flockdeck "$tag")
  rm -rf "$root/app" "$root/self-hosting"
  (cd "$work/flockdeck" && go run ./cmd/docgen -out "$root")
  printf '%s %s\n' "$tag" "$sha" >"$stamp"
  echo "regenerated from flockdeck $tag ($sha); review with git diff, then commit .docs-generated-from with it"
  ;;

check)
  [ -f "$stamp" ] || { echo "$stamp is missing: it records which flockdeck the generated pages came from (see README)" >&2; exit 1; }
  read -r tag sha <<<"$(tr -d "[:cntrl:]" <"$stamp")"
  [ -n "$tag" ] && [ -n "$sha" ] || { echo "$stamp should read '<tag> <commit>', e.g. 'v0.3.40 795f8d6...'" >&2; exit 1; }
  fetch_flockdeck "$tag" "$sha" >/dev/null
  scratch_copy
  generate "$work/site"
  changes=$(changed_pages)
  if [ -n "$changes" ]; then
    echo "The checked-in generated files are not what flockdeck $tag generates:" >&2
    echo "$changes" >&2
    echo >&2
    echo "Either a generated page was edited by hand, or content/self-hosting/*.md (or the docs stamp) changed" >&2
    echo "without regenerating. Fix with: tools/docdrift/generated.sh regenerate $tag" >&2
    echo "and commit the result. Do not edit app/*.html or self-hosting/*.html directly." >&2
    exit 1
  fi
  echo "generated files match flockdeck $tag"
  ;;

upstream)
  report=${2:?usage: generated.sh upstream REPORT}
  read -r stamped _ <<<"$(tr -d "[:cntrl:]" <"$stamp")" || stamped=unknown
  tag=$(latest_tag)
  fetch_flockdeck "$tag" >/dev/null
  scratch_copy
  generate "$work/site"
  changed_pages >"$report"
  printf '%s\n' "$tag" >"${report}.latest"
  printf '%s\n' "$stamped" >"${report}.stamped"
  if [ -s "$report" ]; then
    echo "docs are behind flockdeck $tag (generated from $stamped):"
    cat "$report"
  else
    echo "docs are current with flockdeck $tag"
  fi
  ;;

*)
  sed -n '2,17p' "$0" >&2
  exit 2
  ;;
esac
